export { default as formlabel } from './formlabel.vue';
export { default as formtext } from './formtext.vue';
export { default as formtextarea } from './formtextarea.vue';
export { default as formckeditor } from './formckeditor.vue';
export { default as formnumber } from './formnumber.vue';
export { default as formpassword } from './formpassword.vue';
export { default as formselect } from './formselect.vue';
export { default as formcascader } from './formcascader.vue';
export { default as formradio } from './formradio.vue';
export { default as formcheckbox } from './formcheckbox.vue';
export { default as formtableselector } from './formtableselector';
export { default as formtableinputer } from './formtableinputer';
export { default as formdate } from './formdate.vue';
export { default as formtime } from './formtime.vue';
export { default as formlink } from './formlink.vue';
export { default as formrate } from './formrate.vue';
export { default as formuserselect } from './formuserselect.vue';
export { default as formtreeselect } from './formtreeselect.vue';
export { default as formaccounts } from './formaccounts';
export { default as formupload } from './formupload.vue';
export { default as formdivider } from './formdivider';
export { default as formcube } from './formcube.vue';
export { default as formtab } from './formtab.vue';
export { default as formcollapse } from './formcollapse.vue';
export { default as formtable } from './formtable.vue';

export * from '@/views/pages/cmdb/form/component';
export * from '@/views/pages/autoexec/form/component';
